add solution for background image
js-tasks-ru/htmlcss-20231027_f-tlyashev pull request #17
Opened 2023-11-21 16:43 UTC by TliasheFF

Добавлено решение по задаче background-image

2023-11-21 16:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-22 06:26 UTC, GSemikozov requested changes

2023-11-22 06:26 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width: 576px) {
лишний медиа-запрос, ставим эту картинку по умолчанию на body

2023-11-22 06:26 UTC, GSemikozov commented on 06-lection4/02-background-image/index.html
> +    <link rel="stylesheet" href="../../assets/css/main.css">
не забываем про метатег вьюпорт )

2023-11-22 09:30 UTC, TliasheFF commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width: 576px) {
поправил

2023-11-22 09:30 UTC, TliasheFF commented on 06-lection4/02-background-image/index.html
> +    <link rel="stylesheet" href="../../assets/css/main.css">
точно! добавил )

2023-11-23 20:57 UTC, GSemikozov approved these changes

2023-11-23 20:57 UTC, merged