add solution for input
js-tasks-ru/htmlcss-20231027_f-tlyashev pull request #24
Opened 2023-11-26 12:15 UTC by TliasheFF

2023-11-26 12:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-28 21:36 UTC, GSemikozov requested changes

2023-11-28 21:36 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <svg class='form-group__icon_success'>
а как же класс элемента который модифицируем?) form-group__icon

2023-11-28 21:36 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.form-group__icon_success,
общие стили - в .form-group__icon

2023-11-28 21:36 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.form-group__input > input {
лучше просто класс

2023-11-28 21:36 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +	margin-top: 5px;
а если не будет лейбла? отступ лучше на уровне лейбла

2023-11-28 21:36 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.form-group__input > input::placeholder {
для плейсхолдера меняем только цвет

2023-11-28 21:36 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +input:focus {
см выше

2023-11-29 06:54 UTC, TliasheFF commented on 07-lection5/04-input/index.html
> +            <svg class='form-group__icon_success'>
Пропустил)

2023-11-29 06:54 UTC, TliasheFF commented on 07-lection5/04-input/input.css
> +.form-group__icon_success,
Перенес общие стили в отдельный класс .form-group__icon

2023-11-29 07:10 UTC, TliasheFF commented on 07-lection5/04-input/input.css
> +.form-group__input > input::placeholder {
Поправил

2023-11-29 07:20 UTC, TliasheFF commented on 07-lection5/04-input/input.css
> +.form-group__input > input {
Подправил

2023-11-29 07:20 UTC, TliasheFF commented on 07-lection5/04-input/input.css
> +	margin-top: 5px;
Перенес в лейбл

2023-11-29 07:20 UTC, TliasheFF commented on 07-lection5/04-input/input.css
> +input:focus {
Убрал привязку к input и настроил на класс

2023-12-02 20:46 UTC, GSemikozov approved these changes

2023-12-02 20:47 UTC, merged