add card-grid
js-tasks-ru/htmlcss-20231027_f-tlyashev pull request #7
Opened 2023-11-07 11:11 UTC by TliasheFF

Добавил в index.html карточки и стили к ним.
В index.html добавил инлайн стиль к карточкам чисто чтобы посмотреть как выглядит и временно еще добавил card__footer.

Когда дойдем до начинок карточек - переделаю а инлайн стили уберу.

2023-11-07 11:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 06:57 UTC, GSemikozov requested changes

2023-11-08 06:57 UTC, GSemikozov commented on components/preview/preview.css
> +.card {
а это все-таки отдельный блок) и нельзя описывать стили другого блока в файле стилей данного

2023-11-08 11:44 UTC, TliasheFF commented on components/preview/preview.css
> +.card {
Переименовал селекторы для карточки и футера карточки

2023-11-08 19:52 UTC, GSemikozov approved these changes

2023-11-08 19:52 UTC, merged