add solution for histogram
js-tasks-ru/htmlcss-20231027_f-tlyashev pull request #8
Opened 2023-11-07 14:23 UTC by TliasheFF

Добавлены стили и верстка для компонента "гистограмма"

2023-11-07 14:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 07:01 UTC, GSemikozov requested changes

2023-11-08 07:01 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 24px 6px;
чтобы не задавать паддинги на уровне каждого дочернего элемента, лучше задать эти общие отступы здесь

2023-11-08 07:01 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__all {
.histogram__link?

2023-11-08 07:01 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100px;
сделаем как в макете - 50px

2023-11-08 07:01 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <p class="histogram__all">View all</p>
`<a>`

2023-11-08 11:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 11:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-08 19:53 UTC, GSemikozov approved these changes

2023-11-08 19:53 UTC, merged